name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    services:
      periplus:
        image: periplus_image:latest
        platforms: linux/amd64
        ports:
          - 3000:3000

      proxy:
        image: proxy_image:latest
        ports:
          - 8000:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Periplus image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t periplus_image:latest -f Dockerfile --load .

      - name: Build Proxy image
        run: |
          docker build -t proxy_image:latest -f proxy.Dockerfile .

      - name: Run Periplus container
        run: |
          docker run -d --platform linux/amd64 -p 3000:3000 --name periplus periplus_image:latest

      - name: Run Proxy container
        run: |
          docker run -d -p 8000:8000 --name proxy proxy_image:latest

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run end-to-end tests
        run: |
          python tests/e2e/e2e_test.py

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: reports/
