name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Periplus image
        id: build_periplus_image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t periplus_image:latest -f Dockerfile --load .

      - name: Build Proxy image
        id: build_proxy_image
        run: |
          docker buildx build --platform linux/amd64 -t proxy_image:latest -f proxy.Dockerfile --load .

      - name: Run Periplus container
        run: |
          docker run -d --name periplus -p 3000:3000 periplus_image:latest

      - name: Run Proxy container
        run: |
          docker run -d --name proxy -p 8000:8000 proxy_image:latest

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run end-to-end tests
        run: |
          python test/e2e/e2e_test.py

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: reports/
