name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Periplus image
        id: build_periplus_image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t periplus_image:latest -f Dockerfile --load .

      - name: Build Proxy image
        id: build_proxy_image
        run: |
          docker buildx build --platform linux/amd64 -t proxy_image:latest -f proxy.Dockerfile --load .

      - name: Run Periplus container
        run: |
          docker run -d --name periplus -p 3000:3000 periplus_image:latest

      - name: Run Proxy container
        run: |
          docker run -d --name proxy -p 8000:8000 proxy_image:latest

      - name: Build and Run Test Driver
        run: |
          docker build -t test_driver_image -f driver.Dockerfile .
          docker run --name test_driver_container test_driver_image

      - name: Get Test Driver Exit Code
        id: get_test_driver_exit_code
        run: |
          docker inspect test_driver_container --format='{{.State.ExitCode}}' > exit_code.txt
          cat exit_code.txt
        continue-on-error: true

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: reports/

      - name: Fail the job if tests failed
        if: failure()
        run: |
          exit_code=$(cat exit_code.txt)
          if [ "$exit_code" -ne 0 ]; then
            echo "Tests failed with exit code $exit_code"
            exit $exit_code
          fi
